# Generated by Django 6.1.1 on 2026-10-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=300)),
                ('salary', models.CharField(max_length=50)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobusers.jobuser')),
            ],
        ),
    ]
