# Generated by Django 6.1.1 on 2026-10-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobusers', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Applied', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobusers.jobuser')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobusers.job')),
            ],
        ),
    ]
